site_name: "Plex Guide"
site_url: "https://guide.{{ plex_url }}"
repo_url: "https://github.com/{{ username }}/{{ repo_name }}"
repo_name: !ENV GITHUB_REPOSITORY
theme:
  name: material
  logo: assets/images/plex-logo.webp
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: amber
      accent: orange
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: amber
      accent: deep orange

nav:
  - Intro: index.md
  - What is Plex?: setup/what-is-plex.md
  - Setup:
    - Setup: setup/index.md
    - Using Plex: setup/using-plex.md
    - Pinning Libraries: setup/pinning-libraries.md
    - Quality Settings:
      - setup/quality-settings/index.md
      - Smart TV: setup/quality-settings/smart-tv.md
      - tvOS (Apple TV): setup/quality-settings/tv-os.md
      - Android & iOS: setup/quality-settings/android-ios.md
      - Web Browser: setup/quality-settings/web-browser.md
  - Plex Libraries: plex-libraries.md
  - Plex Collections: plex-collections.md
  - Media Quality: media-quality.md
  - Media Requests:
    - media-requests/index.md
    - media-requests/jellyseerr.md
    - media-requests/issues.md
    - media-requests/requestrr.md
  - Settings:
    - Managing Newsletter Subscriptions: settings/unsubscribe-from-plex-newsletter.md
    - Disabling Online Media Sources: settings/disabling-online-media-sources.md
  - Clients & Hardware: clients-hardware.md
  - FAQ:
    - Is Plex safe to use?: faq/plex-safety.md
    - How do I use subtitles?: faq/how-do-i-use-subtitles.md
    - How do I add items to the Watchlist?: faq/adding-to-watchlist.md
    - I requested something an hour ago but it hasn't shown up yet.: faq/missing-requests.md
    - The Plex app isn't working: faq/client-issues.md
    - My video won't stop buffering: faq/wont-stop-buffering.md
    - What is transcoding?: faq/what-is-transcoding.md
    - Why Bitrate Matters: faq/why-bitrate-matters.md
    - Can I listen to music/podcasts, store photos, or do other stuff?: faq/can-i-do-other-stuff.md
    - Do I need to buy a Plex Pass?: faq/do-i-need-to-buy-plex-pass.md
    - Help, I forgot my Plex password!: faq/forgot-password.md
    - Can I share your Plex server with someone else?: faq/can-i-share-your-plex.md
    - Plex is awesome! Can I send you some money to support it?: faq/how-can-i-support-you.md
    - Where does media come from?: faq/where-does-media-come-from.md
    - Responsible Content Requesting: faq/responsible-content-requests.md
    - Missing Confirmation Emails: faq/missing-emails.md
    - I don't want to use this request thingy, can't I just tell you what I want?: faq/i-dont-want-to-use-jellyseerr.md
  - Useful Links: useful-links.md

plugins:
  - search
  - mkdocs-video
  - markdownextradata: {}
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: !ENV GITHUB_REPOSITORY
      branch: !ENV GITHUB_REF_NAME
      exclude_committers:
        - "web-flow"  # GitHub web UI edits
        - "actions-user"  # GitHub Actions
        - "github-actions[bot]"  # GitHub Actions bot
      # For a repository hosted on GitHub, you can provide a token to increase the rate limit and go beyond the default 60 requests per hour per IP address.
      # The plugin will make one request per mkdocs document
      # See: https://github.com/ojacques/mkdocs-git-committers-plugin-2
      token: !ENV GITHUB_TOKEN

markdown_extensions:
  - toc:
      toc_depth: 1
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: "Copyright &copy; 2025 {{ username }}"

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/{{ username }}"
      name: "{{ username }} @ Github"
    - icon: fontawesome/brands/discord
      link: https://discord.gg/kCBJffcK3N
      name: Discord Channel
    - icon: fontawesome/solid/globe
      link: "https://dnode.me"
      name: Personal Website

  vars:
    username: !ENV GITHUB_REPOSITORY_OWNER
    repo_name: !ENV GITHUB_REPOSITORY
    request_url: "jellyseerr.dnode.me"
    plex_url: "plex.dnode.me"
    plex_libraries: "Movies, Shows"
    noreply_email: "noreply@example.com"

  env:
    branch: !ENV [GITHUB_REF_NAME, 'main']
    commit_sha: !ENV [commit_sha, '']  # Will be empty on main, show SHA on develop
