name: ci

on:
  push:
    branches:
      - main
    tags:
      - '*'  # This will trigger on any tag
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    # Skip if commit message contains [skip ci]
    if: |
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[skip-ci]') &&
      !contains(github.event.head_commit.message, '[no ci]') &&
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate mkdocs.yml
        run: |
          # Get current year
          YEAR=$(date +'%Y')

          # Convert username to lowercase
          USERNAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

          # Process the entire mkdocs.yml file
          cat mkdocs.yml | \
          sed "s/{{ username }}/${USERNAME}/g" | \
          sed "s/{{ repo_name }}/${{ github.event.repository.name }}/g" | \
          sed "s/{{ year }}/${YEAR}/g" \
          > mkdocs.generated.yml
          mv mkdocs.generated.yml mkdocs.yml

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: requirements-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            requirements-

      - run: |
          pip install -r requirements.txt
          pip install git+https://github.com/SivagiriVisakan/mkdocs-replace-plugin.git

      - name: Build and Deploy
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          CURRENT_YEAR: $(date +'%Y')
        run: mkdocs gh-deploy --force
