name: ci

on:
  push:
    branches: [main]
    tags:
      - '*'  # This will trigger on any tag
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    # Skip if commit message contains [skip ci]
    if: |
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[skip-ci]') &&
      !contains(github.event.head_commit.message, '[no ci]') &&
      (
        github.event_name == 'push' ||
        github.event_name == 'workflow_dispatch' ||
        github.event_name == 'pull_request'
      )
    runs-on: ubuntu-latest
    env:
      GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      REQUEST_URL: ${{ vars.REQUEST_URL }}
      PLEX_URL: ${{ vars.PLEX_URL }}
      PLEX_LIBRARIES: ${{ vars.PLEX_LIBRARIES }}
      NOREPLY_EMAIL: ${{ vars.NOREPLY_EMAIL }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate mkdocs.yml
        run: |
          # Get current year
          YEAR=$(date +'%Y')

          # Convert username to lowercase
          USERNAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

          # Process the entire mkdocs.yml file
          cat mkdocs.yml | \
          sed "s/{{ username }}/${USERNAME}/g" | \
          sed "s/{{ repo_name }}/${{ github.event.repository.name }}/g" | \
          sed "s/{{ year }}/${YEAR}/g" \
          > mkdocs.generated.yml
          mv mkdocs.generated.yml mkdocs.yml

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - uses: actions/cache@v4
        with:
          key: pip-wheels-${{ runner.os }}-py3-${{ hashFiles('requirements.txt') }}
          path: |
            ~/.cache/pip
            ~/.local/lib/python*/site-packages
          restore-keys: |
            pip-wheels-${{ runner.os }}-py3-
            pip-wheels-${{ runner.os }}-

      - run: |
          pip install -r requirements.txt

      - name: Build and Deploy
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          CURRENT_YEAR: $(date +'%Y')
        run: mkdocs gh-deploy --force
